# Generated by Django 5.0.2 on 2024-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_user_orgnaization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
