# Generated by Django 5.0.2 on 2024-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_pic_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
