# Generated by Django 5.0.2 on 2024-02-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='core.organization'),
        ),
    ]
