# Generated by Django 5.0.2 on 2024-02-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_created_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orgnaization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
    ]
