# Generated by Django 5.0.2 on 2024-02-16 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visitor_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationpass',
            name='approver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
