# Generated by Django 5.0.2 on 2024-02-16 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invitationpass_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationpass',
            name='approver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitationpass',
            name='checked_in_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invitationpass',
            name='checked_out_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invitationpass',
            name='organization_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.location'),
        ),
    ]
