# Generated by Django 5.0.2 on 2024-02-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_invitationpass_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationpass',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.visitor'),
        ),
    ]
