# Generated by Django 5.0.2 on 2024-02-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_invitationpass_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='origin_user',
            new_name='target_user',
        ),
        migrations.AlterField(
            model_name='invitationpass',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.visitor'),
        ),
    ]
