# Generated by Django 5.0.2 on 2024-02-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_origin_user_notification_target_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target_user',
            new_name='user',
        ),
    ]
