# Generated by Django 5.0.2 on 2024-02-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_user_notification_target_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target_user',
            new_name='targeted_user',
        ),
    ]
