# Generated by Django 5.0.2 on 2024-02-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_designation_user_phone_user_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationpass',
            name='passkey',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
