# Generated by Django 5.0.2 on 2024-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_invitationpass_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationpass',
            name='passkey_varified',
            field=models.BooleanField(default=False),
        ),
    ]
