# Generated by Django 5.0.2 on 2024-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_invitationpass_passkey_varified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationpass',
            name='passkey_varified',
        ),
        migrations.AddField(
            model_name='invitationpass',
            name='passkey_at',
            field=models.DateTimeField(null=True),
        ),
    ]
